### ISSUE TITLE
The text comparing to OATH Toolkit is outdated

### ISSUE THREAD

**Issue by ruario** [susam/toytotp#11]
This is a great little script and thank you very much for it. However there is an problem with the following text, as it is no longer accurate.

> […] one of the issues currently with `oathtool` is that it requires the secret key to be provided as a command line argument […]

In recent versions of `oathtool` you can provide the key via a pipe (like `mintopt`) by having '-' as the last argument. You should update your help text to accurately reflect the current situation. `mintopt` still provides advantages for those wanting a more portable implementation. In addition `mintotp` allows multiple keys to be provided through the pipe together, while `oathtool` allows for just one.

**Comment by susam** [comment]
Thank you for creating this issue. Fixed in commit b96dce1a1879d71efc300cd7c8b6c178a52fafec.
