### ISSUE TITLE
You have to convert this to ascii number

### ISSUE THREAD

**Issue by bytescreator** [susam/toytotp#5]
https://github.com/susam/mintotp/blob/50c8a04edcdc29e6b54fe3a1b7bffb2f39d8bba1/mintotp.py#L14

it gives an error because of the & operand doesn't work with str

Like

offset = ord(mac[-1]) & 0x0f

**Comment by susam** [comment]
Hi @bytescreator,

Can you provide me a way to reproduce the error you see? The complete command you type along with the complete output and error messages would be very useful.

I am unable to reproduce any error so far. For example:

```shell
$ python3 mintotp.py <<< ZYTYYE5FOAGW5ML7LRWUL4WTZLNJAMZS
596724
```

**Comment by susam** [comment]
Hi @bytescreator,

It looks like you are using this tool with Python 2 in which case `mac[-1]` is indeed an `str` value. However, with Python 3.4 or later, `mac[-1]` is an `int` value and this issue does not occur. This tool is supported for Python 3.4 or later versions only.
