### ISSUE TITLE
Digest should be a hash module

### ISSUE THREAD

**Issue by bytescreator** [susam/toytotp#6]
https://github.com/susam/mintotp/blob/50c8a04edcdc29e6b54fe3a1b7bffb2f39d8bba1/mintotp.py#L19

it gives AttributeError: 'str' object has no attribute 'new' on line 13 because of the hmac module calls .new function on the digest we gave.
You gave sha1 string to it but it should be like

+import hashlib # to the start

def hotp(key, counter, digits=6, digest=hashlib.sha1): # at line 10

and

def totp(key, time_step=30, digits=6, digest=hashlib.sha1): # at line 19

**Comment by susam** [comment]
Hi @bytescreator,

It appears to me that you are using Python 2 to run this tool. This tool is supported for Python 3.4 and later versions only. The `hmac` module in Python 3.4 and later supports `str` value for the `digestmod` argument in `hmac.new()`. See https://docs.python.org/3/library/hmac.html#hmac.new for more details.
